### ISSUE TITLE
Meaning of sentence not clear

### ISSUE THREAD

**Issue by carstenmichel** [ibm-watson-embedded-business-assistant/eba-example-agents#6]
Please see [Why EBA](https://github.com/ibm-watson-embedded-business-assistant/eba-example-agents#why-eba) section, 2nd part of last sentence:

"we offer that EBA will prove" sound strange to me

**Comment by mbordash** [comment]
Yes that was a silly way to phrase that sentence.  I've updated it. Should be better.
