### ISSUE TITLE
@react endpoint minor error

### ISSUE THREAD

**Issue by ghost** [ibm-watson-embedded-business-assistant/eba-example-agents#7]
There is an unwanted closing curly bracket in the node code.
module.exports.main = params => {
    const repr = params.input.repr
    if (repr.data.orderMeta)
        return {
            type: 'concept',
            name: ':OrderEvent',
            data: repr.data
        }
    //} this isn't required
    else return {}
}

**Comment by arsu77** [comment]
Thank's @Kamnag. I took the action and corrected it with the last commit.
